### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by ThiagosLima** [leandrotk/learning-functional-programming#15]
Olá, tudo bom?

Muito legal esse repositório! Parabéns!

Tentei acessar o link "Functional Programming Study Plan", na sessão "Foundation" e aparentemente o link está quebrado.

**Comment by imteekay** [comment]
Valeu pelo issue @ThiagosLima! Eu removi o link agora parece que o @ericdouglas arquivou/deletou o repo do site dele e acho que esse link não existe mais. Se o link voltar a prod, adicionamos ele de novo no repo.
